# --- BASE
# A clean image target for Next.js applications
FROM node:lts-alpine3.22 AS base

WORKDIR /app

# Installation de pnpm
RUN npm install -g pnpm

# --- DEV-DEPENDENCIES
# A target that'll have dev-dependencies installed
FROM base AS dev-dependencies

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

# --- PROD-DEPENDENCIES
# A target that'll have only production dependencies installed
FROM base AS prod-dependencies

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --production

# --- DEV
# Target for development with hot reload
FROM base AS dev

COPY package.json pnpm-lock.yaml ./
COPY --from=dev-dependencies /app/node_modules ./node_modules

COPY . .

EXPOSE 3000

CMD ["pnpm", "run", "dev"]

# --- BUILD
# Target to build the Next.js application for production
FROM dev-dependencies AS build

# Accept build arguments for Next.js public env vars
ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

ARG NEXT_PUBLIC_STRIPE_PUBLIC_KEY
ENV NEXT_PUBLIC_STRIPE_PUBLIC_KEY=$NEXT_PUBLIC_STRIPE_PUBLIC_KEY

COPY . .

RUN pnpm run build

# --- RUNNER
# Target for production runtime
# --- RUNNER
# Target for production runtime
FROM base AS runner

COPY --from=prod-dependencies /app/package.json ./package.json
COPY --from=prod-dependencies /app/node_modules ./node_modules

COPY --from=build /app/public ./public
COPY --from=build /app/.next ./.next

EXPOSE 3000

CMD ["pnpm", "start"]