name: YOUR_APP_NAME-dev

services:
  api:
    ports:
      - "8000:80"
    depends_on:
      - db
    build:
      context: ./backend
      target: dev
    container_name: YOUR_APP_NAME-backend-dev

  app:
    ports:
      - "3000:3000"
    depends_on:
      - api
    build:
      context: ./frontend
      dockerfile: dockerfile
      target: dev
    command: pnpm run dev
    container_name: YOUR_APP_NAME-frontend-dev

  db:
    image: mariadb:10.6
    container_name: YOUR_APP_NAME-database-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: YOUR_APP_NAME
      MYSQL_USER: YOUR_APP_NAME
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - ./db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - web
      - internal

  phpmyadmin:
    profiles:
      - dev
    image: phpmyadmin/phpmyadmin
    container_name: YOUR_APP_NAME-phpmyadmin-dev
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - web
      - internal
volumes:
  db_data:
